### ISSUE TITLE
multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by tangchi-coder** [Skinok/backtrader-pyqt-ui#15]
发生异常: SyntaxError
multiple exception types must be parenthesized (__init__.py, line 239)
  File "E:\学习资料\backtrader-pyqt-ui-main\SkinokBacktraderUI.py", line 22, in <module>
    import backtrader as bt
SyntaxError: multiple exception types must be parenthesized (__init__.py, line 239)

**Comment by xiaoqizheng0033** [comment]
这个错误是安装IbPy包引起的，卸载backtrader包，重新安装backtrader即可解决
