### ISSUE TITLE
Import custom fields in CSV file

### ISSUE THREAD

**Issue by antonma** [Skinok/backtrader-pyqt-ui#8]
Hi,

first thank you for this promising framework / tool!
I need to add some additional fields to the CSV file in order to use them in a strategy. How can I achieve that and where do I start. 
For now I get the following error:
![image](https://user-images.githubusercontent.com/13572239/210580192-3970c7c3-e3ae-4a22-9bdc-876c326fa4bd.png)

Thank you and best regards,
Anton

**Comment by Skinok** [comment]
The CSV should only contains raw DATA informations OHLCV, other information should be computed from these data in a strategy python file.
