### ISSUE TITLE
function missing in finplot

### ISSUE THREAD

**Issue by ghmole** [Skinok/backtrader-pyqt-ui#9]
#in finplotwindow.py:
##def zoomTo(self, dateStr1, dateStr2):

        for win in fplt.windows:
            for ax in win.axs:
                x1 = fplt._dateStr2x(ax,dateStr1)
                x2 = fplt._dateStr2x(ax,dateStr2)
##but could not find "_dateStr2x" in finplot

**Comment by Skinok** [comment]
Yes, for now, you should use my own version of finplat.
You can find it in my repositories forks.
I'll try to do a pull request on the main finplot repo for this
